import json
import datetime
import os
from docxtpl import DocxTemplate, InlineImage
from docx.shared import Mm

# Width of the chart inside the downloaded .docx only (does not affect the web preview).
CHART_WIDTH_MM = 140

def generate_document(client: dict | None = None):
    # Paths of the files generated by Rivet
    letter_file = "outputs/letter.json"
    chart_path = "outputs/performance_chart.png"
    
    if not os.path.exists(letter_file):
        print(f"Error: The file {letter_file} was not generated by Rivet.")
        return

    # Reading the data generated by main_challenge
    with open(letter_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    greeting = data.get("greeting", "Prezado Cliente,")
    portfolio_text = data.get("portfolio", "")
    macro_text = data.get("macro_and_risk", "")

    # Generating the document
    template_path = "templates/letter_template.docx"
    if not os.path.exists(template_path):
        print("Error: Template file not found.")
        return
        
    doc = DocxTemplate(template_path)

    # Programmatically generate the date and signature variables
    months = ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"]
    today = datetime.datetime.now()
    current_date = f"{today.day} de {months[today.month - 1]} de {today.year}"
    advisor_name = "Antonio Bicudo"
    advisor_number = "+55 11 99504-3853"
    if client:
        advisor_name = client.get("advisor_name") or advisor_name
        advisor_number = client.get("advisor_phone") or advisor_number

    # Handle chart image
    chart_obj = None
    if os.path.exists(chart_path):
        chart_obj = InlineImage(doc, chart_path, width=Mm(CHART_WIDTH_MM))

    # Map data to template tags
    context = {
        "current_date": current_date,
        "greeting": greeting,
        "portfolio": portfolio_text,
        "macro_and_risk": macro_text,
        "advisor_name": advisor_name,
        "advisor_number": advisor_number,
        "chart": chart_obj
    }

    # Render the document
    doc.render(context)

    # Generate a unique filename and save
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    output_filename = f"outputs/Client_Letter_{timestamp}.docx"
    
    os.makedirs("outputs", exist_ok=True)
    doc.save(output_filename)

    print(f"Success! Document generated and saved as {output_filename}")
    return output_filename
