import pandas as pd
import yfinance as yf
import requests
import json
import datetime
import os
import re

# Brazilian large-cap “coverage” tickers — same Yahoo path as portfolio stocks (.SA).
# Shown in returns CSV/JSON for monitoring; excluded from portfolio weight aggregation.
BRAZIL_STOCK_WATCHLIST = [
    "GGBR4", "ABEV3", "PETR4", "VALE3", "ITUB4", "WEGE3", "B3SA3", "BBAS3",
]

# Rows that participate in Global Portfolio monthly returns (excludes Watchlist and summary rows).
PORTFOLIO_WEIGHT_TYPES = ("Stocks", "Funds", "Fixed Revenue")


def _latest_completed_calendar_month_yyyy_mm(now: datetime.datetime | None = None) -> str:
    """YYYY-MM for the last full calendar month (exclude the current incomplete month)."""
    dt = now or datetime.datetime.now()
    d = dt.date()
    first_this_month = d.replace(day=1)
    last_prev = first_this_month - datetime.timedelta(days=1)
    return last_prev.strftime("%Y-%m")


def _fetch_yahoo_monthly_returns(ticker_base: str, months_found: set) -> dict:
    """
    Download ~6 months of monthly closes for a B3 ticker (ticker_base + '.SA').
    Returns a dict of { 'YYYY-MM': float_return, ... } for months with data.
    """
    out = {}
    ticker = ticker_base + ".SA"
    try:
        hist = yf.download(ticker, period="6mo", interval="1mo", progress=False)
        if hist.empty or len(hist) < 2:
            return out
        if isinstance(hist.columns, pd.MultiIndex):
            close_prices = hist["Close"][ticker]
        else:
            close_prices = hist["Close"]
        returns = close_prices.pct_change().dropna().tail(5)
        for date, ret in returns.items():
            month_str = date.strftime("%Y-%m")
            months_found.add(month_str)
            if not pd.isna(ret):
                out[month_str] = float(ret)
    except Exception as e:
        print(f"Error fetching {ticker}: {e}")
    return out


def generate_returns_csv():
    """
    Fetches market data, calculates portfolio returns, and saves to CSV and JSON.
    """
    positions_file = "outputs/positions.json"
    if not os.path.exists(positions_file):
        print(f"Error: The file {positions_file} was not generated by Rivet.")
        return
        
    with open(positions_file, 'r', encoding='utf-8') as f:
        try:
            positions = json.load(f)
        except Exception:
            print("Error parsing positions.json")
            return

    # Map fund names to their CNPJ for API lookups
    funds_map = {
        "Riza Lotus Plus Advisory FIC FIRF REF DI CP": "43.917.493/0001-31",
        "Brave 90 FIC FIDC": "35.726.300/0001-37",
        "Trend Investback FIC FIRF Simples": "37.910.132/0001-60",
        "Truxt Long Bias Advisory FIC FIM": "30.830.162/0001-18",
        "STK Long Biased FIC FIA": "12.282.747/0001-69",
        "Constellation Institucional Advisory FIC FIA": "34.462.109/0001-62",
        "Ibiuna Hedge ST Advisory FIC FIM": "30.493.349/0001-73"
    }

    # Fetch IPCA from BACEN SGS (Series 433)
    ipca_data = {}
    try:
        ipca_url = "https://api.bcb.gov.br/dados/serie/bcdata.sgs.433/dados/ultimos/10?formato=json"
        res = requests.get(ipca_url, timeout=10)
        if res.status_code == 200:
            for item in res.json():
                dt = datetime.datetime.strptime(item['data'], "%d/%m/%Y")
                month_str = dt.strftime('%Y-%m')
                ipca_data[month_str] = float(item['valor']) / 100
    except Exception as e:
        print(f"Error fetching IPCA: {e}")

    # Fetch CDI from BACEN SGS (Series 4391)
    cdi_data = {}
    try:
        cdi_url = "https://api.bcb.gov.br/dados/serie/bcdata.sgs.4391/dados/ultimos/10?formato=json"
        res = requests.get(cdi_url, timeout=10)
        if res.status_code == 200:
            for item in res.json():
                dt = datetime.datetime.strptime(item['data'], "%d/%m/%Y")
                month_str = dt.strftime('%Y-%m')
                cdi_data[month_str] = float(item['valor']) / 100
    except Exception as e:
        print(f"Error fetching CDI: {e}")

    rows = []
    months_found = set()
    
    today = datetime.datetime.now()
    end_date = today.strftime("%Y%m%d")
    start_date = (today - datetime.timedelta(days=365)).strftime("%Y%m%d")
    
    print("\nGenerating returns table...")
    for item in positions:
        row = {
            "Type": item.get("type", ""),
            "Name": item.get("name", ""),
            "Value": item.get("value", "")
        }
        
        if item.get("type") == "Stocks":
            raw_name = item.get("name")
            # Ticker corrections
            if raw_name == "ARZZ3":
                raw_name = "AZZA3"
            elif raw_name == "MRFG3":
                raw_name = "MBRF3"

            row["Name"] = raw_name
            print(f"Fetching data for {raw_name}.SA...")
            for month_str, ret in _fetch_yahoo_monthly_returns(raw_name, months_found).items():
                row[month_str] = ret
                
        elif item.get("type") == "Funds":
            fund_name = item.get("name")
            if fund_name == "Brave I FIC FIM CP":
                fund_name = "Brave 90 FIC FIDC"
                row["Name"] = fund_name
                
            cnpj_raw = funds_map.get(fund_name)
            if cnpj_raw:
                cnpj_clean = re.sub(r'[^0-9]', '', cnpj_raw)
                print(f"Fetching Fund {fund_name[:15]}... ({cnpj_clean})")
                
                # Hardcoded bypass for Brave 90 FIC FIDC due to API block
                if fund_name == "Brave 90 FIC FIDC":
                    print(f"  -> Using hardcoded manual data for {fund_name}.")
                    hardcoded_returns = {
                        "2025-11": 0.0117,
                        "2025-12": 0.0135,
                        "2026-01": 0.0129,
                        "2026-02": 0.0110,
                        "2026-03": 0.0133,
                        "2026-04": 0.0114
                    }
                    for month_str, ret in hardcoded_returns.items():
                        months_found.add(month_str)
                        row[month_str] = ret
                    rows.append(row)
                    continue
                
                try:
                    url = f"https://www.okanebox.com.br/api/fundoinvestimento/hist/{cnpj_clean}/{start_date}/{end_date}/"
                    res = requests.get(url, timeout=15)
                    
                    if res.status_code == 200:
                        if len(res.text) < 5:
                            print(f"  -> [WARNING] Okane API returned NO DATA for {fund_name}. This CNPJ ({cnpj_clean}) might require a premium token.")
                        else:
                            data = res.json()
                            if data:
                                df_fund = pd.DataFrame(data)
                                df_fund['DT_COMPTC'] = pd.to_datetime(df_fund['DT_COMPTC'])
                                df_fund.set_index('DT_COMPTC', inplace=True)
                                monthly = df_fund['VL_QUOTA'].groupby(df_fund.index.to_period('M')).last()
                                ret_series = monthly.pct_change().dropna().tail(5)
                                for period, ret in ret_series.items():
                                    month_str = period.strftime('%Y-%m')
                                    months_found.add(month_str)
                                    if not pd.isna(ret):
                                        row[month_str] = ret
                    else:
                        print(f"  -> [ERROR] Okane API returned status {res.status_code} for {fund_name}")
                except Exception as e:
                    print(f"Error fetching fund {fund_name}: {e}")
                    
        elif item.get("type") == "Fixed Revenue":
            print("Calculating CDB IPCA+5.55%...")
            fix_rate_monthly = (1 + 0.0555) ** (1/12) - 1
            ipca_items = list(ipca_data.items())[-5:]
            for month_str, ipca_val in ipca_items:
                months_found.add(month_str)
                total_ret = ((1 + ipca_val) * (1 + fix_rate_monthly)) - 1
                row[month_str] = total_ret
                
        rows.append(row)

    portfolio_stock_names = set()
    for item in positions:
        if item.get("type") != "Stocks":
            continue
        nm = item.get("name") or ""
        if nm == "ARZZ3":
            nm = "AZZA3"
        elif nm == "MRFG3":
            nm = "MBRF3"
        portfolio_stock_names.add(nm)

    for sym in BRAZIL_STOCK_WATCHLIST:
        if sym in portfolio_stock_names:
            continue
        wl_row = {
            "Type": "Watchlist",
            "Name": sym,
            "Value": "R$0,00",
        }
        print(f"Fetching watchlist {sym}.SA...")
        for month_str, ret in _fetch_yahoo_monthly_returns(sym, months_found).items():
            wl_row[month_str] = ret
        rows.append(wl_row)

    df = pd.DataFrame(rows)
    
    # Parse Value to float for calculating weights
    df['Value_Num'] = df['Value'].str.replace('R$', '', regex=False).str.replace(',', '', regex=False).astype(float)
    total_value = df['Value_Num'].sum()
    df['Weight'] = df['Value_Num'] / total_value
    
    max_report_month = _latest_completed_calendar_month_yyyy_mm()
    sorted_months = sorted(m for m in months_found if m <= max_report_month)
    excluded = sorted(m for m in months_found if m > max_report_month)
    if excluded:
        print(
            f"Reporting window ends at {max_report_month}; "
            f"excluding incomplete/future month columns: {', '.join(excluded)}"
        )
    last_month = sorted_months[-1] if sorted_months else None
    
    # Fill missing month columns (float NaN — compatible with .astype / to_numeric)
    for month in sorted_months:
        if month not in df.columns:
            df[month] = float("nan")

    # Column-wise: pd.to_numeric does not accept a whole DataFrame in some pandas versions
    df_returns = df[sorted_months].apply(lambda col: pd.to_numeric(col, errors="coerce"))

    # Extract CDI returns for benchmark (months from Yahoo may extend beyond BACEN window)
    cdi_series_data = [cdi_data.get(month, float("nan")) for month in sorted_months]
    cdb_returns = pd.to_numeric(pd.Series(cdi_series_data, index=sorted_months), errors="coerce")
    
    # Cumulative returns
    df['Cumulative_Return'] = (1 + df_returns.fillna(0)).prod(axis=1) - 1
    cdb_cum_return = (1 + cdb_returns.fillna(0)).prod() - 1
    
    # Return vs CDB
    if last_month:
        df['Last Month vs CDB'] = df[last_month] - cdb_returns[last_month]
        df['Last Month Return'] = df[last_month]
    else:
        df['Last Month vs CDB'] = pd.NA
        df['Last Month Return'] = pd.NA
    df['Cumulative vs CDB'] = df['Cumulative_Return'] - cdb_cum_return
    
    # Global Portfolio Return row
    port_row = {
        'Type': 'Portfolio',
        'Name': 'Global Portfolio Return',
        'Value': f"R${total_value:,.2f}",
        'Weight': 1.0
    }
    
    portfolio_monthly = {}
    for m in sorted_months:
        mask = df["Type"].isin(PORTFOLIO_WEIGHT_TYPES) & df[m].notna()
        active_weights = df.loc[mask, "Weight"]
        if active_weights.sum() > 0:
            rebased_weights = active_weights / active_weights.sum()
            weighted_ret = (df.loc[mask, m] * rebased_weights).sum()
            portfolio_monthly[m] = weighted_ret
            port_row[m] = weighted_ret
        else:
            portfolio_monthly[m] = 0.0
            port_row[m] = pd.NA
            
    port_cum_return = (1 + pd.Series(portfolio_monthly)).prod() - 1
    port_row['Cumulative_Return'] = port_cum_return
    
    if last_month:
        port_row['Last Month vs CDB'] = portfolio_monthly.get(last_month, 0.0) - cdb_returns[last_month]
        port_row['Last Month Return'] = portfolio_monthly.get(last_month, pd.NA)
    else:
        port_row['Last Month vs CDB'] = pd.NA
        port_row['Last Month Return'] = pd.NA
    port_row['Cumulative vs CDB'] = port_cum_return - cdb_cum_return

    # Reference row: BACEN CDI (same series as chart benchmark) for CSV / JSON visibility
    cdi_row = {
        "Type": "Benchmark",
        "Name": "CDI (Benchmark)",
        "Value": "—",
        "Weight": float("nan"),
    }
    for m in sorted_months:
        cdi_row[m] = cdb_returns.get(m, float("nan"))
    cdi_row["Cumulative_Return"] = cdb_cum_return
    if last_month:
        cdi_row["Last Month Return"] = cdb_returns.get(last_month, float("nan"))
    else:
        cdi_row["Last Month Return"] = pd.NA
    cdi_row["Last Month vs CDB"] = pd.NA
    cdi_row["Cumulative vs CDB"] = pd.NA

    # Append global portfolio row, then CDI benchmark reference
    df = pd.concat([df, pd.DataFrame([port_row]), pd.DataFrame([cdi_row])], ignore_index=True)
    
    # Save raw data for charting before formatting
    chart_data = {
        'df': df.copy(),
        'sorted_months': sorted_months,
        'cdi_returns': cdb_returns
    }
    
    # Formatting columns for user display
    cols_to_pct = ['Weight', 'Last Month Return', 'Cumulative_Return', 'Last Month vs CDB', 'Cumulative vs CDB'] + sorted_months
    for c in cols_to_pct:
        df[c] = df[c].apply(lambda x: f"{x*100:.2f}%" if pd.notna(x) else "-")
        
    final_columns = ["Type", "Name", "Value", "Weight"] + sorted_months + ["Last Month Return", "Cumulative_Return", "Last Month vs CDB", "Cumulative vs CDB"]
    final_columns = [c for c in final_columns if c in df.columns]
    df = df[final_columns]
    
    # Rename columns to be user friendly
    df = df.rename(columns={'Cumulative_Return': 'Cumulative Return'})
    
    rename_months = {}
    month_names = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]
    for month in sorted_months:
        y, m = month.split('-')
        month_name = month_names[int(m)-1]
        rename_months[month] = f"{month_name}/{y[-2:]}"
        
    df = df.rename(columns=rename_months)
    
    out_csv = "outputs/portfolio_returns.csv"
    try:
        df.to_csv(out_csv, index=False, sep=";", encoding="utf-8-sig")
        print(f"Returns CSV table saved at {out_csv}")
    except PermissionError:
        print(f"PERMISSION ERROR: The file {out_csv} is open in Excel. Please close it and try again.")
        
    # Generate JSON summary for Rivet
    if len(sorted_months) >= 2:
        period_str = f"from {rename_months[sorted_months[0]]} to {rename_months[last_month]}"
    else:
        period_str = ""
        
    summary_data = []
    for idx, row in df.iterrows():
        if row["Type"] == "Watchlist":
            continue
        cum_return = row['Cumulative Return']
        if cum_return != "-":
            cum_return = f"{cum_return} ({period_str})"
            
        summary_data.append({
            "Type": row["Type"],
            "Name": row["Name"],
            "Value": row["Value"],
            "Weight": row["Weight"],
            "Last Month Return": row["Last Month Return"],
            "Cumulative Return": cum_return,
            "Last Month vs CDI": row["Last Month vs CDB"],
            "Cumulative vs CDI": row["Cumulative vs CDB"]
        })
        
    summary_file = "outputs/performance_summary.json"
    try:
        with open(summary_file, 'w', encoding='utf-8') as f:
            json.dump(summary_data, f, ensure_ascii=False, indent=2)
        print(f"Performance summary JSON saved at {summary_file}")
    except Exception as e:
        print(f"Error saving performance summary JSON: {e}")

    return chart_data

if __name__ == "__main__":
    generate_returns_csv()
